__author__ = 'Samuel'
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ('                                                        Classification of Business')
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ('Primary, Secondary, and Tertiary Sectors')
print ('- Primary sector activity involves harvesting of natural resources')
print ('- Secondary sector activity is the refinement of raw materials into goods')
print ('- Tertiary sector activity involves providing services to the final consumer or business (shops, restaurants, banks, airlines)')
print ('    ')
print ('How the Sectors Depend On Each Other')
print ('- Raw materials move from primary to secondary to tertiary sectors in a chain of production')
print ('- Without all three sectors the chain of production collapses and goods are not made')
print ('    ')
print ('Changing Importance of Business Classification')
print ('- A developing country will have a smaller industrial sector while a developed country will have a highly industrialized society')
print ('- The size of an industrial sector often indicates the level of development of a country')
print ('- Industrialization is the growing importance of the secondary sector and the reduced importance of the primary sector')
print ('- De-industrialization is the growing importance of the tertiary sector and the reduced importance of the secondary sector')
print ('    ')
print ('Business Enterprises in the Private and Public Sectors')
print ('- A mixed economy is one that has both private and public sector organizations')
print ('- The private sector is made up of businesses controlled by the government and are mainly operating to serve the people instead of turning a profit')
print ('- The private sector is made up of businesses that are owned by people who are selling goods and services to the public to turn a profit')
print ('- These businesses sell to consumers and compete with other businesses')
hold = input()
import BSCptr1_3