__author__ = 'Samuel'
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ("Welcome to Chapter One. This Chapter is split up into 5 sections. Once you finish reading this section, press enter to move on to the next.")
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ('                                                            Buisness Activity')
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ('Needs and Wants')
print ('- Needs are a good or service someone needs to survive')
print ('- Wants are services and goods people would like to purchase, but are not necessary to survival')
print ('- These two terms are integral to supply and demand')
print ('    ')
print ('Scarcity and Opportunity Cost')
print ('- Scarcity is a lack of goods and Surplus is an excess of goods')
print ('- Land (natural resources), Labor (people that can work), Capital (machinery), and Enterprise (people setting up the business/ Entrepreneurs')
print ('are the four factors of production and control scarcity')
print ('- When choosing between two or more items, the items not chosen are called the opportunity cost')
print ('    ')
print ('Importance of Specialization')
print ('- Businesses specialize their production of goods to make sure no factors of production are wasted on unnessesary goods that consumers do')
print ('not want')
print ('- Instead of companies creating everytype of good, they specialize and only create one or two types of goods')
print ('    ')
print ('Importance of Business Activity')
print ('- Without business activity, goods and services would not be produced for consumers to buy')
print ('- Goods and services are split into Consumer Goods (Goods for people), Consumer Services (Services for people), and')
print ('- Capital goods (Goods for businesses')
print ('    ')
print ('Adding Value')
print ('- Companies try to add artificial value to their products')
print ('- They can do this by adding their brand name, Having excellent service quality, extra features, and making it convenient')
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
hold = input()
import BSCptr1_2