__author__ = 'Samuel'
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ('                                                Enterprise, Business Growth and Size')
print ("-----------------------------------------------------------------------------------------------------------------------------------------------")
print ('Enterprise and Entrepreneurship')
print ('- New businesses are started by people called entrepreneurs')
print ('- They have an idea for a new business, invest their own savings, accept the risk of failure, and manage the business')
print ('- A new business is called an enterprise')
print ('- An enterprise can be anything, including a new idea for a good or service, offering an existing good in a different way, or offering an')
print ('existing good or service in a new location')
print ('- An entrepreneur must be innovative, determined, self confident, multi-skilled, a risk taker and good at networking')
print ('    ')
print ('Business Plans')
print ('- Business plans describe the business, the business opportunity, the market, the objectives of the business, and financial forecasts')
print ('- The information it contains can give a new business direction, targets to aim for, and help borrow money from lenders')
print ('- Business plans are used for both new and established businesses (when used with an existing business it is called a corporate plan)')
print ('    ')
print ('How Governments Support Start-ups')
print ('- Governments like start-ups because they create jobs, create new goods and services, increase competition among businesses, and can create')
print ('specialty products')
hold = input()